[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MikesToolsLibrary"
version = "0.1.0"
description = "A collection of tools by Mike"
authors = [{ name = "Mike Merrett", email = "public@merrett.ca" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = []
keywords = ["logging", "formatter", "python", "decorator", "custom levels"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/yourusername/MikesToolsLibrary"
Repository = "https://github.com/yourusername/MikesToolsLibrary"
Issues = "https://github.com/yourusername/MikesToolsLibrary/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["MikesToolsLibrary*"]

[tool.setuptools.package-data]
"MikesToolsLibrary" = ["py.typed"]

[project.scripts]
basic-setup = "examples.basic_setup:main"

