[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MikesToolslibrary"
version = "0.1.0"
description = "A collection of tools by Mike"
authors = [{ name="Mike", email="mike@example.com" }]
readme = "README.md"
license = { text = "MIT" }
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]